networks:
  proxy:
    name: proxy
    external: ${NETWORK_EXTERNAL:-false}

include:
#  - dnsmasq/docker-compose.yml
  # - socket-proxy/docker-compose.yml
  - caddy/docker-compose.yml
  - 3xui/docker-compose.yml
  - dozzle/docker-compose.yml
#  - frps/docker-compose.yml
#  - frpc/docker-compose.yml
#  - portainer-agent/docker-compose.yml
#  - beszel/docker-compose.yml
#  - beszel-agent/docker-compose.yml
#  - rustdesk/docker-compose.yml
