networks:
  frontend:
    name: frontend
    external: ${NETWORK_EXTERNAL:-false}
  backend:
    name: backend
    external: ${NETWORK_EXTERNAL:-false}

include:
  - caddy/docker-compose.yml
  - dozzle/docker-compose.yml
  - 3xui/docker-compose.yml
  - docker-socket-proxy/docker-compose.yml
  - beszel-agent/docker-compose.yml
#  - beszel/docker-compose.yml
#  - rustdesk/docker-compose.yml
#  - gotify/docker-compose.yml


