services:
  caddy:
    build:
      context: .
    container_name: caddy
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - PREFIX_SITE_XUI_WEB=${PREFIX_SITE_XUI_WEB}
      - PREFIX_SITE_XUI_SUB=${PREFIX_SITE_XUI_SUB}
      - PREFIX_SITE_DOZZLE=${PREFIX_SITE_DOZZLE}
      # (绕开宿主机的代理) dozzle/3xui(caddyfile 使用它们的服务) 是 Docker 内网服务名，.${SITE_ADDRESS} 覆盖公开域名。
      - NO_PROXY=localhost,127.0.0.1,dozzle,3xui,.${SITE_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${CONFIG_PATH}caddy:/etc/caddy
      - ${DATA_PATH}caddy:/data/caddy
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
