services:
  caddy:
    build:
      context: .
    container_name: caddy
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - PREFIX_SITE_DOZZLE=${PREFIX_SITE_DOZZLE}
      - PREFIX_SITE_XUI=${PREFIX_SITE_XUI}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${CONFIG_PATH}caddy:/etc/caddy
      - ${DATA_PATH}caddy:/data/caddy
    restart: always
    networks:
      - frontend
      - backend
