services:
  caddy:
    build:
      context: .
    container_name: caddy
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - PREFIX_SITE_XUI_WEB=${PREFIX_SITE_XUI_WEB}
      - PREFIX_SITE_XUI_SUB=${PREFIX_SITE_XUI_SUB}
      - PREFIX_SITE_DOZZLE=${PREFIX_SITE_DOZZLE}
      - PREFIX_SITE_FRPS=${PREFIX_SITE_FRPS}
      - PREFIX_SITE_RUSTDESK=${PREFIX_SITE_RUSTDESK}
      # (绕开宿主机的代理) dozzle/frps/3xui/hbbs(caddyfile 使用它们的服务) 是 Docker 内网服务名，.${SITE_ADDRESS} 覆盖公开域名。
      - NO_PROXY=localhost,127.0.0.1,dozzle,frps,3xui,hbbs,.${SITE_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "7000:7000"
    volumes:
      - ${CONFIG_PATH}caddy:/etc/caddy
      - ${DATA_PATH}caddy:/data/caddy
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
