#<hash_algorithm> is the name of the password hashing algorithm (or KDF)
#                   used for the hashes in this configuration. Default: bcrypt
#<realm> is a custom realm name.
#<username> is a username or user ID.
#<hashed_password> is the password hash.
# docker compose run --rm --no-deps caddy caddy hash-password --plaintext 'Admin123!'
basic_auth {
	# Username "bob", password "Bob123!"
	bob $2a$14$MHo.fh8zKTNf3pge4meOMeQPYoa64.DahDcHl6xhSPnCAZBDuch.2
	# Username "admin", password "Admin123!"
	admin $2a$14$z8vyInprKI8XC4KfLmUGzO6x1Ju4sktJzBA/8aiG/zLXxpBhdduPO
}
