services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3xui
    volumes:
      - ${DATA_PATH}/3xui/db/:/etc/x-ui/
      - ${DATA_PATH}/3xui/cert/:/root/cert/
    ports:
      - "49001-49020:49001-49020"
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_ENABLE_FAIL2BAN=true
    tty: true
    restart: unless-stopped
    networks:
      - frontend
      - backend
