services:
  gotify:
    image: gotify/server:2.8
    container_name: gotify
    restart: always
    ports:
      - "8380:80"
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_DEFAULTUSER_NAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
      - TZ=Asia/Shanghai
    volumes:
      - "${DATA_PATH}gotify:/app/data"
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`gotify.${DOMAIN:-test.local}`)"
      - "traefik.http.routers.gotify.entrypoints=websecure"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
