# http:
#   routers:
#     dozzle:
#       rule: "Host(`dozzle.${DOMAIN:-localhost}`)"
#       entryPoints:
#         - websecure
#       service: dozzle
#       tls:
#         certResolver: letsencrypt

#   services:
#     dozzle:
#       loadBalancer:
#         servers:
#           - url: "http://dozzle:8080" # 这里 'dozzle' 是容器名，Traefik 在同一网络内可直接解析
