services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    user: root
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "42375:2375"
    environment:
      - LOG_LEVEL=debug
      - CONTAINERS=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - VOLUMES=1
      - SYSTEM=1
      - EVENTS=1
      - PING=1
      - VERSION=1
      - POST=1
      - EXEC=1
    networks:
      - proxy
