services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:v0.4.2
    container_name: socket-proxy
    user: root
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOG_LEVEL=info
      - CONTAINERS=1
      - INFO=1
      - EVENTS=1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider -Y off http://127.0.0.1:2375/_ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - proxy
