services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    ports:
      - "8180:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_LEVEL: debug
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_ENABLE_SHELL: true
      DOZZLE_NO_ANALYTICS: true
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
    networks:
      - proxy