services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.5.3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8180:8080"
    environment:
      NO_PROXY: localhost,127.0.0.1,socket-proxy
      DOZZLE_NO_ANALYTICS: true
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
    networks:
      - proxy
