(proxy-app-authelia-auth) {
	{args[0]} {
		import ../snippets/request-log.conf
		import ../snippets/security.conf
		encode zstd gzip
		forward_auth authelia:9091 {
			uri /api/authz/forward-auth
			copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
		}
		reverse_proxy {args[1]} {
			header_up Cookie "authelia_session=[^;]+" "authelia_session=_"
			header_up X-Accel-Buffering "no"
			flush_interval -1
			transport http {
				dial_timeout 10s
				response_header_timeout 30s
				read_timeout 1h
				write_timeout 1h
			}
		}
	}
}
