services:
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:v1.7.6-slim
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      GID: "${GID-1000}"
      BOUNCER_KEY_TRAEFIK: ${CROWDSEC_LAPI_KEY}
      COLLECTIONS: "crowdsecurity/traefik LePresidente/authelia"
    volumes:
      - ${CONFIG_PATH}acquis.yml:/etc/crowdsec/acquis.yaml
      - ${data_path}:/var/lib/crowdsec/data/
      - ${CONFIG_PATH}crowdsec/config:/etc/crowdsec/
    networks:
      - backend
    healthcheck:
      test: ["CMD", "cscli", "version"]
    security_opt:
      - no-new-privileges:true